version: "3.8"

services:
  app_blue:
    build: .
    container_name: stage-2-app_blue
    image: mabirhire1/node-test-image-blue:latest
    environment:
      - PORT=3000
      - COLOR=blue
      - VERSION=1.0.0
    ports:
      - "8081:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  app_green:
    build: .
    container_name: stage-2-app_green
    image: mabirhire1/node-test-image-green:latest
    environment:
      - PORT=3000
      - COLOR=green
      - VERSION=1.0.0
    ports:
      - "8082:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/version"]
      interval: 30s
      timeout: 10s
      retries: 3
